### ISSUE TITLE
Landing page

### ISSUE THREAD

**Issue by utk7arsh** [uclaacm/dev-pathways-next#2]
## Aim

Welcome to Dev Pathways. These are some UI bugs on the landing page which could be fixed by css changes, state handling, etc. This issue details the tasks we need to complete in order to reach this milestone.

## Tasks

- [x] Horizontal overflow on every page - On the landing page, the crucial resources button overlows to the right which can totally be avoided by a minor css. I feel like this issue is in every page on the web right now

- [x] If you click the button "Generate" at the bottom of the page. and come back to the home page, you will find it disappeared. Attached image for reference
![Screenshot 2024-02-22 at 10 42 02 AM](https://github.com/uclaacm/dev-pathways-next/assets/66383982/c18a5c86-ccb1-4f1d-8090-a45b80c8376c)

![Screenshot 2024-02-22 at 10 41 42 AM](https://github.com/uclaacm/dev-pathways-next/assets/66383982/c068191f-f957-4946-84dd-5ed2dff893e5)

- [x] The images aren't loading when we switched from React to nextjs. This needs to be looked into and at certain times, the issue can be the image compatiblity with next. For example the social media images aren't generated
![Screenshot 2024-02-22 at 10 43 30 AM](https://github.com/uclaacm/dev-pathways-next/assets/66383982/e6849bc5-9996-43df-965d-d61752b48496)
